D4PrototypeLearningPlatform/Pages/Cursussen/Create.cshtml.cs
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace D4PrototypeLearningPlatform.Pages.Cursussen;

public class CreateModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public CreateModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult OnGet()
    {
        return Page();
    }

    [BindProperty]
    public Cursus Cursus { get; set; }


    // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        _context.Cursus.Add(Cursus);
        await _context.SaveChangesAsync();

        return RedirectToPage("./Index");
    }
}

D4PrototypeLearningPlatform/Pages/Cursussen/Delete.cshtml.cs
using D4PrototypeLearningPlatform.Data;
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Cursussen;

public class DeleteModel : PageModel
{
    private readonly ApplicationDbContext _context;

    public DeleteModel(ApplicationDbContext context)
    {
        _context = context;
    }

    [BindProperty]
    public Cursus Cursus { get; set; } = default!;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Cursus == null)
        {
            return NotFound();
        }
        // 
        var cursus = await _context.Cursus.FirstOrDefaultAsync(m => m.Id == id);

        if (cursus == null)
        {
            return NotFound();
        }
        else
        {
            Cursus = cursus;
        }
        return Page();
    }

    public async Task<IActionResult> OnPostAsync(Guid? id)
    {
        if (id == null || _context.Cursus == null)
        {
            return NotFound();
        }
        // findasync is not working with the include statement for no reason!
        var cursus = await _context.Cursus.Include(x => x.Modules).FirstOrDefaultAsync(m => m.Id == id);

        if (cursus != null)
        {
            Cursus = cursus;
            _context.Cursus.Remove(Cursus);
            await _context.SaveChangesAsync();
        }

        return RedirectToPage("./Index");
    }
}

D4PrototypeLearningPlatform/Pages/Cursussen/Details.cshtml.cs
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Cursussen;

public class DetailsModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public DetailsModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    public Cursus Cursus { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Cursus == null)
        {
            return NotFound();
        }

        var cursus = await _context.Cursus.FirstOrDefaultAsync(m => m.Id == id);
        if (cursus == null)
        {
            return NotFound();
        }
        else
        {
            Cursus = cursus;
        }
        return Page();
    }
}

D4PrototypeLearningPlatform/Pages/Cursussen/Edit.cshtml.cs
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Cursussen;

public class EditModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public EditModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    [BindProperty]
    public Cursus Cursus { get; set; } = default!;


    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Cursus == null)
        {
            return NotFound();
        }

        var cursus = await _context.Cursus.Include(x => x.Modules).FirstOrDefaultAsync(m => m.Id == id);
        if (cursus == null)
        {
            return NotFound();
        }
        Cursus = cursus;
        return Page();
    }

    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see https://aka.ms/RazorPagesCRUD.
    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        _context.Attach(Cursus).State = EntityState.Modified;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!CursusExists(Cursus.Id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }

        return Redirect($"./Edit?Id={Cursus.Id}");
    }

    public async Task<IActionResult> OnPostAddModuleAsync()
    {
        Module module = new()
        {
            Name = "New Name",
        };

        var cursus = _context.Cursus.First(x => x.Id == Cursus.Id);
        cursus.Modules.Add(module);

        _context.Cursus.Update(cursus);
        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            // this is not right
            if (!CursusExists(cursus.Id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }
        return Redirect($"./Edit?Id={Cursus.Id}");
    }

    private bool CursusExists(Guid id)
    {
        return _context.Cursus.Any(e => e.Id == id);
    }
}

D4PrototypeLearningPlatform/Pages/Modules/Create.cshtml.cs
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace D4PrototypeLearningPlatform.Pages.Modules;

public class CreateModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public CreateModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult OnGet()
    {
        return Page();
    }

    [BindProperty]
    public Module Module { get; set; }


    // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        _context.Module.Add(Module);
        await _context.SaveChangesAsync();

        return RedirectToPage("./Index");
    }
}

D4PrototypeLearningPlatform/Pages/Modules/Delete.cshtml.cs
using D4PrototypeLearningPlatform.Data;
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Modules;

public class DeleteModel : PageModel
{
    private readonly ApplicationDbContext _context;

    public DeleteModel(ApplicationDbContext context)
    {
        _context = context;
    }

    [BindProperty]
    public Module Module { get; set; } = default!;

    [FromQuery]
    [BindProperty(Name = "cursus", SupportsGet = true)]
    public string CursusId { get; set; } = string.Empty;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Module == null)
        {
            return NotFound();
        }

        var module = await _context.Module.FirstOrDefaultAsync(m => m.Id == id);

        if (module == null)
        {
            return NotFound();
        }
        else
        {
            Module = module;
        }
        return Page();
    }

    public async Task<IActionResult> OnPostAsync(Guid? id)
    {
        if (id == null || _context.Module == null)
        {
            return NotFound();
        }
        var module = await _context.Module.Include(x => x.Opgaves).FirstOrDefaultAsync(m => m.Id == id);

        if (module != null)
        {
            Module = module;
            _context.Module.Remove(Module);
            await _context.SaveChangesAsync();
        }
        if (CursusId == null)
        {
            return RedirectToPage("./Index");
        }
        else
        {
            return Redirect("/Cursussen/Edit?id=" + CursusId);
        }
    }
}

D4PrototypeLearningPlatform/Pages/Modules/Details.cshtml.cs
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Modules;

public class DetailsModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public DetailsModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    public Module Module { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Module == null)
        {
            return NotFound();
        }

        var module = await _context.Module.FirstOrDefaultAsync(m => m.Id == id);
        if (module == null)
        {
            return NotFound();
        }
        else
        {
            Module = module;
        }
        return Page();
    }
}

D4PrototypeLearningPlatform/Pages/Modules/Edit.cshtml.cs
using D4PrototypeLearningPlatform.Data;
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Modules;

public class EditModel : PageModel
{
    private readonly ApplicationDbContext _context;

    public EditModel(ApplicationDbContext context)
    {
        _context = context;
    }

    // https://localhost:7117/Cursussen/Edit?id=9f674a56-5f98-4c97-97fd-51efdc36f73e
    [BindProperty]
    public Module Module { get; set; } = default!;

    [FromQuery]
    [BindProperty(Name = "cursus", SupportsGet = true)]
    public string CursusId { get; set; } = string.Empty;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Module == null)
        {
            return NotFound();
        }

        var module = await _context.Module.Include(x => x.Opgaves).FirstOrDefaultAsync(m => m.Id == id);
        if (module == null)
        {
            return NotFound();
        }
        Module = module;
        return Page();
    }

    // To protect from overposting attacks, enable the specific properties you want to bind to.
    // For more details, see https://aka.ms/RazorPagesCRUD.
    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        _context.Attach(Module).State = EntityState.Modified;

        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            if (!ModuleExists(Module.Id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }

        if (string.IsNullOrEmpty(CursusId))
        {
            return Redirect($"./Edit?Id={Module.Id}");
        }
        return Redirect($"./Edit?Id={Module.Id}&cursus={CursusId}");
    }

    public async Task<IActionResult> OnPostAddOpgaveAsync()
    {
        Opgave opgave = new()
        {
            Name = "New Name",
        };
        var module = _context.Module.Include(m => m.Opgaves).First(x => x.Id == Module.Id);
        module.Opgaves.Add(opgave);

        _context.Module.Update(module);
        try
        {
            await _context.SaveChangesAsync();
        }
        catch (DbUpdateConcurrencyException)
        {
            // this is not right
            if (!ModuleExists(Module.Id))
            {
                return NotFound();
            }
            else
            {
                throw;
            }
        }
        if (string.IsNullOrEmpty(CursusId))
        {
            return Redirect($"./Edit?Id={Module.Id}");
        }
        return Redirect($"./Edit?Id={Module.Id}&cursus={CursusId}");
    }

    private bool ModuleExists(Guid id)
    {
        return _context.Module.Any(e => e.Id == id);
    }
}

D4PrototypeLearningPlatform/Pages/Modules/Index.cshtml.cs
using D4PrototypeLearningPlatform.Model;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Modules;

public class IndexModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public IndexModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    public IList<Module> Module { get; set; } = default!;

    public async Task OnGetAsync()
    {
        if (_context.Module != null)
        {
            Module = await _context.Module.ToListAsync();
        }
    }
}

D4PrototypeLearningPlatform/Pages/Opgaven/Create.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace D4PrototypeLearningPlatform.Pages.Opgaven;

public class CreateModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public CreateModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    public IActionResult OnGet()
    {
        return Page();
    }

    [BindProperty]
    public Opgave Opgave { get; set; }


    // To protect from overposting attacks, see https://aka.ms/RazorPagesCRUD
    public async Task<IActionResult> OnPostAsync()
    {
        if (!ModelState.IsValid)
        {
            return Page();
        }

        _context.Opgave.Add(Opgave);
        await _context.SaveChangesAsync();

        return RedirectToPage("./Index");
    }
}

D4PrototypeLearningPlatform/Pages/Opgaven/Delete.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Opgaven;

public class DeleteModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public DeleteModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    [BindProperty] 
    public Opgave Opgave { get; set; } = default!;

    [FromQuery]
    [BindProperty(Name = "module", SupportsGet = true)]
    public string ModuleId { get; set; } = string.Empty;

    [FromQuery]
    [BindProperty(Name = "cursus", SupportsGet = true)]
    public string CursusId { get; set; } = string.Empty;

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Opgave == null)
        {
            return NotFound();
        }

        var opgave = await _context.Opgave.FirstOrDefaultAsync(m => m.Id == id);

        if (opgave == null)
        {
            return NotFound();
        }
        else
        {
            Opgave = opgave;
        }
        return Page();
    }

    public async Task<IActionResult> OnPostAsync(Guid? id)
    {
        if (id == null || _context.Opgave == null)
        {
            return NotFound();
        }
        var opgave = await _context.Opgave.FindAsync(id);

        if (opgave != null)
        {
            Opgave = opgave;
            _context.Opgave.Remove(Opgave);
            await _context.SaveChangesAsync();
        }


        if (ModuleId == null || CursusId == null)
        {
            return RedirectToPage("./Index");
        }
        else
        {
            return Redirect($"/Modules/Edit?id={ModuleId}&cursus={CursusId}");
        }
    }
}

D4PrototypeLearningPlatform/Pages/Opgaven/Details.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;

namespace D4PrototypeLearningPlatform.Pages.Opgaven;

public class DetailsModel : PageModel
{
    private readonly D4PrototypeLearningPlatform.Data.ApplicationDbContext _context;

    public DetailsModel(D4PrototypeLearningPlatform.Data.ApplicationDbContext context)
    {
        _context = context;
    }

    public Opgave Opgave { get; set; }

    public async Task<IActionResult> OnGetAsync(Guid? id)
    {
        if (id == null || _context.Opgave == null)
        {
            return NotFound();
        }

        var opgave = await _context.Opgave.FirstOrDefaultAsync(m => m.Id == id);
        if (opgave == null)
        {
            return NotFound();
        }
        else
        {
            Opgave = opgave;
        }
        return Page();
    }
}

D4PrototypeLearningPlatform/Pages/Modules/Create.cshtml
@page
@model D4PrototypeLearningPlatform.Pages.Modules.CreateModel

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Module</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Module.Name" class="control-label"></label>
                <input asp-for="Module.Name" class="form-control" />
                <span asp-validation-for="Module.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Module.Description" class="control-label"></label>
                <input asp-for="Module.Description" class="form-control" />
                <span asp-validation-for="Module.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

D4PrototypeLearningPlatform/Pages/Modules/Delete.cshtml
@page
@model D4PrototypeLearningPlatform.Pages.Modules.DeleteModel

@{
    ViewData["Title"] = "Delete";
}

@if (Model.CursusId != "")
{
    <div>
        <a asp-page="/Cursussen/Edit" asp-route-id="@Model.CursusId">Back to Cursus</a>
    </div>
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Module</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Module.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Module.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Module.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Module.Description)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Module.Id" />
        <input type="hidden" asp-for="CursusId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

D4PrototypeLearningPlatform/Pages/Modules/Details.cshtml
@page
@model D4PrototypeLearningPlatform.Pages.Modules.DetailsModel

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Module</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Module.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Module.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Module.Description)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Module.Description)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Module?.Id">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

D4PrototypeLearningPlatform/Pages/Modules/Edit.cshtml
@page
@model D4PrototypeLearningPlatform.Pages.Modules.EditModel

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Module</h4>
@if (Model.CursusId != "")
{
    <div>
        <a asp-page="/Cursussen/Edit" asp-route-id="@Model.CursusId">Back to Cursus</a>
    </div>
}
else
{
    <div>
        <a asp-page="./Index">Back to List</a>
    </div>

}

<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Module.Id" />
            <input type="hidden" asp-for="CursusId" />
            <div class="form-group">
                <label asp-for="Module.Name" class="control-label"></label>
                <input asp-for="Module.Name" class="form-control" />
                <span asp-validation-for="Module.Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Module.Description" class="control-label"></label>
                <input asp-for="Module.Description" class="form-control" />
                <span asp-validation-for="Module.Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>

        <h4>Linked Opgaves!</h4>
        <table class="table">
            <thead>
                <tr>
                    <th>
                        @Html.DisplayNameFor(model => model.Module.Opgaves[0].Name)
                    </th>
                    <th>
                        @Html.DisplayNameFor(model => model.Module.Opgaves[0].Description)
                    </th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model.Module.Opgaves)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.Name)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Description)
                        </td>
                        <td>
                            <a asp-page="/Opgaven/Edit" asp-route-id="@item.Id" asp-route-cursus="@Model.CursusId" asp-route-module="@Model.Module.Id">Edit</a> |
                            @*<a asp-page="/Opgaven/Details" asp-route-id="@item.Id">Details</a> |*@
                            <a asp-page="/Opgaven/Delete" asp-route-id="@item.Id" asp-route-cursus="@Model.CursusId" asp-route-module="@Model.Module.Id">Delete</a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <form method="post" asp-page-handler="AddOpgave" asp-route-cursus="@Model.CursusId">
            <input type="hidden" asp-for="Module.Id" />
            <div class="form-group">
                <input type="submit" value="Add New Opgave" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

D4PrototypeLearningPlatform/Pages/Modules/Index.cshtml
@page
@model D4PrototypeLearningPlatform.Pages.Modules.IndexModel

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-page="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Module[0].Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Module[0].Description)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model.Module) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Description)
            </td>
            <td>
                <a asp-page="./Edit" asp-route-id="@item.Id">Edit</a> |
                <a asp-page="./Details" asp-route-id="@item.Id">Details</a> |
                <a asp-page="./Delete" asp-route-id="@item.Id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>